In [1]:
import requests 
import pandas as pd
import numpy as np

In [2]:
# Performance is v141

headers = {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'}
   
def get_screener(page):
    screen = requests.get(f'https://finviz.com/screener.ashx?v=141&f=exch_nasd&t=AAPL,ADBE,ADI,ADP,ADSK,AEP,ALGN,AMAT,AMD,AMGN,AMZN,ANSS,ASML,ATVI,AVGO,BIDU,BIIB,BKNG,CDNS,CDW,CERN,CHKP,CHTR,CMCSA,COST,CPRT,CSCO,CSX,CTAS,CTSH,DLTR,DOCU,DXCM,EA,EBAY,EXC,FAST,FB,FISV,FOX,FOXA,GILD,GOOG,GOOGL,HON,IDXX,ILMN,INCY,INTC,INTU,ISRG,JD,KDP,KHC,KLAC,LRCX,LULU,MAR,MCHP,MDLZ,MELI,MNST,MRNA,MRVL,MSFT,MTCH,MU,MXIM,NFLX,NTES,NVDA,NXPI,OKTA,ORLY,PAYX,PCAR,PDD,PEP,PTON,PYPL,QCOM,REGN,ROST,SBUX,SGEN,SIRI,SNPS,SPLK,SWKS,TCOM,TEAM,TMUS,TSLA,TXN,VRSK,VRSN,VRTX,WBA,WDAY,XEL,XLNX,ZM&r={page}', headers = headers).text


    tables = pd.read_html(screen)
    tables = tables[-2]
    tables.columns = tables.iloc[0]
    tables = tables[1:]
    
    return tables

In [3]:
qqq1 = get_screener('0')
qqq2 = get_screener('21')
qqq3 = get_screener('41')
qqq4 = get_screener('61')
qqq5 = get_screener('81')
qqq6 = get_screener('101')

In [5]:
qqq = pd.DataFrame()

qqq = pd.concat([qqq1, qqq2, qqq3, qqq4, qqq5, qqq6], axis=0)
qqq = qqq.dropna()
qqq

,No.,Ticker,Perf Week,Perf Month,Perf Quart,Perf Half,Perf Year,Perf YTD,Volatility W,Volatility M,Recom,Avg Volume,Rel Volume,Price,Change,Volume
1,1,AAPL,1.24%,-0.17%,19.14%,10.18%,31.75%,12.21%,1.30%,1.66%,2.00,77.85M,1.50,149.05,0.11%,28053366
2,2,ADBE,0.36%,4.19%,33.78%,27.73%,42.44%,26.84%,1.47%,1.57%,1.70,1.89M,0.50,636.38,0.32%,225621
3,3,ADI,-0.79%,1.46%,14.97%,6.16%,41.40%,14.11%,1.88%,2.12%,1.70,3.09M,0.73,170.36,1.06%,541069
4,4,ADP,0.75%,5.09%,11.62%,28.84%,53.96%,21.96%,1.04%,1.33%,2.90,1.48M,0.46,215.84,0.44%,162316
5,5,ADSK,0.98%,11.76%,23.11%,10.61%,43.39%,8.75%,2.01%,2.18%,2.00,1.12M,0.49,332.12,0.02%,131833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,98,WBA,5.09%,5.20%,-8.90%,-1.60%,17.93%,23.67%,1.98%,1.75%,2.90,5.73M,1.07,49.24,-0.16%,1468291
19,99,WDAY,-0.28%,1.42%,5.73%,-14.73%,32.02%,-1.79%,2.12%,2.42%,1.90,1.59M,0.46,237.36,0.86%,174104
20,100,XEL,-0.65%,1.03%,-3.28%,11.73%,-3.76%,3.18%,1.06%,1.63%,2.90,2.41M,0.50,69.14,0.51%,287471
1,101,XLNX,-3.33%,9.95%,27.34%,1.21%,37.64%,2.95%,2.69%,4.10%,2.90,2.25M,1.03,147.90,1.34%,559168
2,102,ZM,-8.98%,0.62%,25.06%,-16.15%,53.29%,7.57%,4.11%,4.00%,2.20,3.20M,0.54,359.71,-0.87%,412262

In [4]:
qqq.to_csv(r'C:\Users\Luke\Desktop\Personal\qqq.csv')

In [9]:
qq = pd.DataFrame()

qq['Perf Month'] = qqq['Perf Month']
qq['Perf Quart'] = qqq['Perf Quart']
qq['Perf Half'] = qqq['Perf Half']
qq['Perf Year'] = qqq['Perf Year']
qq

   Perf Month Perf Quart Perf Half Perf Year
1      -0.17%     19.14%    10.18%    31.75%
2       4.19%     33.78%    27.73%    42.44%
3       1.46%     14.97%     6.16%    41.40%
4       5.09%     11.62%    28.84%    53.96%
5      11.76%     23.11%    10.61%    43.39%
..        ...        ...       ...       ...
18      5.20%     -8.90%    -1.60%    17.93%
19      1.42%      5.73%   -14.73%    32.02%
20      1.03%     -3.28%    11.73%    -3.76%
1       9.95%     27.34%     1.21%    37.64%
2       0.62%     25.06%   -16.15%    53.29%

[102 rows x 4 columns]

In [28]:
qq.to_csv(r'C:\Users\Luke\Desktop\Personal\qqq.csv')

In [33]:
q = pd.read_csv(r'C:\Users\Luke\Desktop\Personal\qqq1.csv')
q['Comp Score'] = q.mean(axis=1)

     Perf Month  Perf Quart  Perf Half  Perf Year  Comp Score
0          0.00        0.19       0.10       0.32      0.1525
1          0.04        0.34       0.28       0.42      0.2700
2          0.01        0.15       0.06       0.41      0.1575
3          0.05        0.12       0.29       0.54      0.2500
4          0.12        0.23       0.11       0.43      0.2225
..          ...         ...        ...        ...         ...
97         0.05       -0.09      -0.02       0.18      0.0300
98         0.01        0.06      -0.15       0.32      0.0600
99         0.01       -0.03       0.12      -0.04      0.0150
100        0.10        0.27       0.01       0.38      0.1900
101        0.01        0.25      -0.16       0.53      0.1575

[102 rows x 5 columns]

In [35]:
q.to_csv((r'C:\Users\Luke\Desktop\Personal\Nas.csv'))

In [40]:
# Performance is v141

headers = {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'}
   
def get_screener(page):
    screen = requests.get(f'https://finviz.com/screener.ashx?v=121&ft=4&t=MRNA,TEAM,ALGN,ASML,TSLA,NVDA,INTU,GOOG,DOCU,IDXX,MRVL,CDW,MELI,AMAT', headers = headers).text


    tables = pd.read_html(screen)
    tables = tables[-2]
    tables.columns = tables.iloc[0]
    tables = tables[1:]
    
    return tables

In [41]:
sheep = get_screener('0')
sheep

,No.,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS this Y,EPS next Y,EPS past 5Y,EPS next 5Y,Sales past 5Y,Price,Change,Volume
1,1,ALGN,56.18B,80.26,52.79,2.52,16.17,16.44,-,62.76,305.50%,22.22%,66.20%,31.83%,23.90%,704.27,2.40%,473694
2,2,AMAT,117.79B,26.93,17.59,1.08,5.94,9.89,17.41,34.53,38.20%,11.71%,28.40%,24.88%,12.20%,129.22,-4.15%,12946768
3,3,ASML,332.99B,57.46,39.34,1.93,16.96,22.46,52.38,46.51,37.90%,24.16%,21.50%,29.80%,17.30%,781.07,-1.03%,759056
4,4,CDW,27.83B,30.28,23.85,2.38,1.41,26.39,55.53,33.80,9.20%,9.08%,18.30%,12.71%,7.30%,197.91,1.00%,616295
5,5,DOCU,58.15B,-,134.52,-,35.78,236.43,74.48,190.77,-11.10%,31.16%,-7.50%,56.00%,42.10%,295.54,0.85%,1069327
6,6,GOOG,1899.99B,36.88,29.15,1.76,9.66,8.08,-,-,48.30%,9.20%,-,21.00%,-,2767.79,0.51%,726408
7,7,IDXX,59.21B,80.59,72.28,4.68,19.43,77.13,255.10,85.28,37.30%,11.72%,26.70%,17.22%,11.10%,675.67,1.56%,263659
8,8,INTU,147.74B,68.75,49.59,4.33,16.62,14.72,35.89,63.74,17.30%,14.51%,36.80%,15.87%,12.90%,536.92,0.88%,519381
9,9,MELI,93.42B,-,400.41,-,16.91,1130.47,47.46,462.72,99.60%,4161.11%,-14.90%,20.50%,43.60%,1842.67,-2.38%,323158
10,10,MRNA,158.13B,48.86,18.27,2.91,22.53,40.77,20.44,80.69,-26.10%,-19.82%,-,16.80%,-,391.42,1.58%,34227282
11,11,MRVL,49.47B,-,32.27,-,15.92,2.79,94.68,132.41,-117.70%,33.26%,22.10%,36.10%,2.70%,59.86,0.12%,6477599
12,12,NVDA,502.63B,94.38,46.01,3.61,26.10,26.33,39.27,98.17,52.50%,9.46%,44.90%,26.14%,27.20%,199.05,1.05%,15098016
13,13,TEAM,86.53B,-,163.30,-,41.42,288.92,70.23,108.10,-94.70%,29.13%,38.15%,20.00%,35.50%,338.04,1.65%,578525
14,14,TSLA,695.77B,377.75,104.27,7.30,16.62,28.28,42.87,76.18,165.00%,32.12%,19.70%,51.76%,50.80%,722.25,2.04%,17536087

In [42]:
qqq_f = pd.DataFrame()

qqq_f['Ticker'] = sheep['Ticker']
qqq_f['P/E'] = sheep['P/E']
qqq_f['Fwd P/E'] = sheep['Fwd P/E']
qqq_f.to_csv((r'C:\Users\Luke\Desktop\Personal\qqq_f.csv'))

In [43]:
qqq_v = pd.DataFrame()

qqq_v['Ticker'] = sheep['Ticker']
qqq_v['EPS this Y'] = sheep['EPS this Y']
qqq_v['EPS next Y'] = sheep['EPS next Y']
qqq_v['EPS next 5Y'] = sheep['EPS next 5Y']
qqq_v['EPS past 5Y'] = sheep['EPS past 5Y']
qqq_v.to_csv((r'C:\Users\Luke\Desktop\Personal\qqq_v.csv'))

In [45]:
qqq_vv = pd.read_csv(r'C:\Users\Luke\Desktop\Personal\qqq_vv.csv')
qqq_vv.dtypes

Ticker          object
EPS this Y     float64
EPS next Y     float64
EPS next 5Y    float64
EPS past 5Y    float64
dtype: object

In [46]:
qqq_vv['Comp EPS'] = qqq_vv.mean(axis=1)
qqq_vv.to_csv(r'C:\Users\Luke\Desktop\Personal\qqq_vvv.csv')