In [1]:
import requests 
import pandas as pd
import numpy as np

In [2]:
# Performance is v141

headers = {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'}
   
def get_screener(page):
    screen = requests.get(f'https://finviz.com/screener.ashx?v=141&f=exch_nasd&t=AAPL,ADBE,ADI,ADP,ADSK,AEP,ALGN,AMAT,AMD,AMGN,AMZN,ANSS,ASML,ATVI,AVGO,BIDU,BIIB,BKNG,CDNS,CDW,CERN,CHKP,CHTR,CMCSA,COST,CPRT,CSCO,CSX,CTAS,CTSH,DLTR,DOCU,DXCM,EA,EBAY,EXC,FAST,FB,FISV,FOX,FOXA,GILD,GOOG,GOOGL,HON,IDXX,ILMN,INCY,INTC,INTU,ISRG,JD,KDP,KHC,KLAC,LRCX,LULU,MAR,MCHP,MDLZ,MELI,MNST,MRNA,MRVL,MSFT,MTCH,MU,MXIM,NFLX,NTES,NVDA,NXPI,OKTA,ORLY,PAYX,PCAR,PDD,PEP,PTON,PYPL,QCOM,REGN,ROST,SBUX,SGEN,SIRI,SNPS,SPLK,SWKS,TCOM,TEAM,TMUS,TSLA,TXN,VRSK,VRSN,VRTX,WBA,WDAY,XEL,XLNX,ZM&r={page}', headers = headers).text


    tables = pd.read_html(screen)
    tables = tables[-2]
    tables.columns = tables.iloc[0]
    tables = tables[1:]
    
    return tables

In [3]:
qqq1 = get_screener('0')
qqq2 = get_screener('21')
qqq3 = get_screener('41')
qqq4 = get_screener('61')
qqq5 = get_screener('81')
qqq6 = get_screener('101')

In [5]:
qqq = pd.DataFrame()

qqq = pd.concat([qqq1, qqq2, qqq3, qqq4, qqq5, qqq6], axis=0)
qqq = qqq.dropna()
qqq

,No.,Ticker,Perf Week,Perf Month,Perf Quart,Perf Half,Perf Year,Perf YTD,Volatility W,Volatility M,Recom,Avg Volume,Rel Volume,Price,Change,Volume
1,1,AAPL,1.24%,-0.17%,19.14%,10.18%,31.75%,12.21%,1.30%,1.66%,2.00,77.85M,1.50,149.05,0.11%,28053366
2,2,ADBE,0.36%,4.19%,33.78%,27.73%,42.44%,26.84%,1.47%,1.57%,1.70,1.89M,0.50,636.38,0.32%,225621
3,3,ADI,-0.79%,1.46%,14.97%,6.16%,41.40%,14.11%,1.88%,2.12%,1.70,3.09M,0.73,170.36,1.06%,541069
4,4,ADP,0.75%,5.09%,11.62%,28.84%,53.96%,21.96%,1.04%,1.33%,2.90,1.48M,0.46,215.84,0.44%,162316
5,5,ADSK,0.98%,11.76%,23.11%,10.61%,43.39%,8.75%,2.01%,2.18%,2.00,1.12M,0.49,332.12,0.02%,131833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,98,WBA,5.09%,5.20%,-8.90%,-1.60%,17.93%,23.67%,1.98%,1.75%,2.90,5.73M,1.07,49.24,-0.16%,1468291
19,99,WDAY,-0.28%,1.42%,5.73%,-14.73%,32.02%,-1.79%,2.12%,2.42%,1.90,1.59M,0.46,237.36,0.86%,174104
20,100,XEL,-0.65%,1.03%,-3.28%,11.73%,-3.76%,3.18%,1.06%,1.63%,2.90,2.41M,0.50,69.14,0.51%,287471
1,101,XLNX,-3.33%,9.95%,27.34%,1.21%,37.64%,2.95%,2.69%,4.10%,2.90,2.25M,1.03,147.90,1.34%,559168
2,102,ZM,-8.98%,0.62%,25.06%,-16.15%,53.29%,7.57%,4.11%,4.00%,2.20,3.20M,0.54,359.71,-0.87%,412262

In [4]:
qqq.to_csv(r'C:\Users\Luke\Desktop\Personal\qqq.csv')

In [9]:
qq = pd.DataFrame()

qq['Perf Month'] = qqq['Perf Month']
qq['Perf Quart'] = qqq['Perf Quart']
qq['Perf Half'] = qqq['Perf Half']
qq['Perf Year'] = qqq['Perf Year']
qq

   Perf Month Perf Quart Perf Half Perf Year
1      -0.17%     19.14%    10.18%    31.75%
2       4.19%     33.78%    27.73%    42.44%
3       1.46%     14.97%     6.16%    41.40%
4       5.09%     11.62%    28.84%    53.96%
5      11.76%     23.11%    10.61%    43.39%
..        ...        ...       ...       ...
18      5.20%     -8.90%    -1.60%    17.93%
19      1.42%      5.73%   -14.73%    32.02%
20      1.03%     -3.28%    11.73%    -3.76%
1       9.95%     27.34%     1.21%    37.64%
2       0.62%     25.06%   -16.15%    53.29%

[102 rows x 4 columns]

In [28]:
qq['Comp Score'] = qq.mean(axis=1)

In [28]:
scores = pd.DataFrame()

scores['Ticker'] = qqq['Ticker']
scores['Comp Score'] = qq['Comp Score']
scores