In [ ]:
import requests 
import pandas as pd
import numpy as np

In [ ]:
# Performance is v141

headers = {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'}
   
def get_screener(page):
    screen = requests.get(f'https://finviz.com/screener.ashx?v=141&f=idx_sp500&ft=4&r={page}', headers = headers).text


    tables = pd.read_html(screen)
    tables = tables[-2]
    tables.columns = tables.iloc[0]
    tables = tables[1:]
    
    return tables

In [ ]:
#Import all the companies in the s and p 500 from finviz 

spy1 = get_screener('0')
spy2 = get_screener('21')
spy3 = get_screener('41')
spy4 = get_screener('61')
spy5 = get_screener('81')
spy6 = get_screener('101')
spy7 = get_screener('121')
spy8 = get_screener('141')
spy9 = get_screener('161')
spy10 = get_screener('181')
spy11 = get_screener('201')
spy12 = get_screener('221')
spy13 = get_screener('241')
spy14 = get_screener('261')
spy15 = get_screener('281')
spy16 = get_screener('301')
spy17 = get_screener('321')
spy18 = get_screener('341')
spy19 = get_screener('361')
spy20 = get_screener('381')
spy21 = get_screener('401')
spy22 = get_screener('421')
spy23 = get_screener('441')
spy24 = get_screener('461')
spy25 = get_screener('481')
spy26 = get_screener('501')

In [217]:
# Concate all the seperate pages into one dataframe 

spy = pd.DataFrame()

spy = pd.concat([spy1, spy2, spy3, spy4, spy5, spy6, spy7, spy8, spy9, spy10, spy11, spy12, spy13, spy14, spy15, spy16, spy17, spy18, spy19, spy20, spy21, spy22, spy23, spy24, spy25, spy26], axis=0)
spy = spy.dropna()
spy

,Ticker,Perf Week,Perf Month,Perf Quart,Perf Half,Perf Year,Perf YTD,Volatility W,Volatility M,Recom,Avg Volume,Rel Volume,Price,Change,Volume,No.
1,AJG,2.09%,1.89%,-2.98%,21.65%,32.31%,14.40%,1.15%,1.71%,2.20,1.25M,0.74,141.52,-0.53%,926091,21
2,AKAM,3.44%,1.09%,5.62%,15.59%,9.61%,11.71%,1.19%,1.69%,2.00,1.16M,0.71,117.28,0.79%,821643,22
3,ALB,8.20%,29.60%,50.00%,47.98%,159.88%,60.34%,5.00%,4.47%,2.50,1.10M,0.99,236.54,0.23%,1080807,23
4,ALGN,0.72%,10.89%,27.21%,17.57%,128.67%,31.79%,2.43%,3.07%,2.00,580.14K,0.82,704.27,2.40%,473694,24
5,ALK,1.75%,1.77%,-12.79%,1.53%,52.29%,12.63%,3.26%,3.93%,1.80,1.85M,0.63,58.57,-1.48%,1171123,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,YUM,-0.21%,13.87%,12.93%,26.43%,43.15%,22.84%,0.87%,1.77%,2.60,1.61M,0.56,133.36,-0.51%,903953,501
2,ZBH,-2.50%,-5.89%,-11.60%,-9.74%,5.65%,-4.98%,1.65%,2.03%,1.80,1.34M,1.61,146.41,0.49%,2152268,502
3,ZBRA,-0.14%,7.22%,20.43%,20.92%,100.13%,47.89%,1.57%,2.29%,2.00,239.50K,0.62,568.40,-0.20%,148168,503
4,ZION,5.31%,8.92%,-5.31%,14.37%,61.26%,28.78%,2.78%,3.34%,2.70,1.31M,0.51,55.94,-0.04%,664049,504
5,ZTS,-1.96%,-0.72%,16.97%,21.53%,25.40%,20.75%,1.74%,1.62%,1.90,1.76M,0.47,199.84,1.23%,829880,505

In [ ]:
# Determine a composite score of the 4 performance metrics by finding the mean 

comp_score = pd.DataFrame()

comp_score['Perf Month'] = spy['Perf Month'] 
comp_score['Perf Quart'] = spy['Perf Quart']
comp_score['Perf Half'] = spy['Perf Half']
comp_score['Perf Year'] = spy['Perf Year']
comp_score['Comp Score'] = spy.mean(axis=1)
# comp_score.to_csv(r'C:\Users\Luke\Desktop\Personal\comp.csv')

In [ ]:
sp['Comp Score'] = sp.mean(axis=1)
sp

In [ ]:
scores = pd.DataFrame()

scores['Ticker'] = spy1['Ticker']
scores['Comp Score'] = sp['Comp Score']
scores

In [ ]:
scores.to_csv(r'C:\Users\Luke\Desktop\Personal\S&P_Comp_Scores.csv')

In [216]:
scores

    Ticker Comp Score
0        A     28.75%
1      AAL     16.50%
2      AAP     18.50%
3     AAPL     15.25%
4     ABBV      7.50%
..     ...        ...
499    YUM     24.00%
500    ZBH     -5.50%
501   ZBRA     37.00%
502   ZION     19.75%
503    ZTS     15.75%

[504 rows x 2 columns]